// <auto-generated />
using InsuranceClaim_Microservice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InsuranceClaim_Microservice.Migrations
{
    [DbContext(typeof(InsurerDBContext))]
    [Migration("20210712122648_miglocal")]
    partial class miglocal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InsuranceClaim_Microservice.Models.InitiateClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ailment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int>("InsurerId")
                        .HasColumnType("int");

                    b.Property<string>("InsurerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatmentPackageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TreatmentPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InsurerId");

                    b.ToTable("InitiateClaims");
                });

            modelBuilder.Entity("InsuranceClaim_Microservice.Models.InsurerDetail", b =>
                {
                    b.Property<int>("InsurerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisbursementDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("InsuranceAmountLimit")
                        .HasColumnType("float");

                    b.Property<string>("InsurerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsurerPackageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsurerId");

                    b.ToTable("InsurerDetails");
                });

            modelBuilder.Entity("InsuranceClaim_Microservice.Models.InitiateClaim", b =>
                {
                    b.HasOne("InsuranceClaim_Microservice.Models.InsurerDetail", "Insurer")
                        .WithMany()
                        .HasForeignKey("InsurerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insurer");
                });
#pragma warning restore 612, 618
        }
    }
}
